name = "Origins Cerberus"
author = "ImUrX"
version = "1.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "589c5e0301919a71cfbea43bd1051341a599aafa1f6ef046e042edd9590b0f17"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
