name = "Origins Cerberus"
author = "ImUrX"
version = "1.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04279beb5adcb92c0da8d2bb81b1539863494d649cac66e4c7eec321cfaed761"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
