name = "Origins Cerberus"
author = "ImUrX"
version = "1.4.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b611290a51eac89bd128e6213dcbe13ac0c4290842853d58d63150033eb977c9"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
