name = "Origins Cerberus"
author = "ImUrX"
version = "1.4.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "356179de8f02cb765fa3c8d126e4a3bf761299ccff1a351799a7d115add668f9"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
