name = "Origins Cerberus"
author = "ImUrX"
version = "1.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7355d7660a5f7e4e736b0139e5ecdc8f26c93a37c63eec7c38fde75693ba71"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
