name = "Origins Cerberus"
author = "ImUrX"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f9d76aa380fb76d89196ae86daa2ef1355986447ca8b4245f35d5cf947f6db5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18.1"]
