name = "Origins Cerberus"
author = "ImUrX"
version = "1.3.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5af0f0cf3359d1316cc79c544de5de8a674eb9008b0d35d39effb5a97aad9883"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
