name = "Origins Cerberus"
author = "ImUrX"
version = "1.3.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb84e8abeb158e1ffaeb8a2c30ac273abde4e823ab4aea708f26e116da993a40"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
