name = "Origins Cerberus"
author = "ImUrX"
version = "2.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43767e05322a4d298a53d8f7d87a0dc35558f3204c4a34bc362ac838ecb2eb3b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18.1", "1.18"]
