name = "Origins Cerberus"
author = "ImUrX"
version = "1.3.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "136bb59869ac439753bb3928b557d8c6c4d5bef881a74148f220cde7dcdd1123"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
