name = "Origins Cerberus"
author = "ImUrX"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a370278df52c06d19a1d8c2f94b120ab1ae032a93b964320b150b30086913af"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18.1", "1.18"]
