name = "Origins Cerberus"
author = "ImUrX"
version = "1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26df6688a6f27529ecbbd61281bf277e370b2a8ae73103ff14dbb477cc25607c"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
