name = "Origins Cerberus"
author = "ImUrX"
version = "1.3.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f8f19b36e479bd70c3ae382ae63b779b24f6a2b1a80ac9e6b2393a273cdd1a9"

[versions]
fabric = "0.12.0"
minecraft = "1.17.1"
