name = "Antique Atlas"
filename = "antiqueatlas-6.1.0-fabric-mc1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3446/120/antiqueatlas-6.1.0-fabric-mc1.17.1.jar"
hash-format = "murmur2"
hash = "1769977129"

[update]
[update.curseforge]
file-id = 3446120
project-id = 227795
release-channel = "beta"
