name = "BetterEnd"
filename = "better-end-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/741/better-end-1.0.1.jar"
hash-format = "murmur2"
hash = "440498400"

[update]
[update.curseforge]
file-id = 3613741
project-id = 413596
release-channel = "beta"
