name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.48+v211013.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3490/246/fabric-carpet-1.17.1-1.4.48+v211013.jar"
hash-format = "murmur2"
hash = "2825465380"

[update]
[update.curseforge]
file-id = 3490246
project-id = 349239
release-channel = "beta"
