name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.50+v211021.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3497/967/fabric-carpet-1.17.1-1.4.50+v211021.jar"
hash-format = "murmur2"
hash = "3055305730"

[update]
[update.curseforge]
file-id = 3497967
project-id = 349239
release-channel = "beta"
