name = "Carpet Extra"
filename = "carpet-extra-1.17.1-1.4.43.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3380/959/carpet-extra-1.17.1-1.4.43.jar"
hash-format = "murmur2"
hash = "3447803903"

[update]
[update.curseforge]
file-id = 3380959
project-id = 349240
release-channel = "beta"
