name = "Carrier"
filename = "carrier-1.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/495/carrier-1.9.0.jar"
hash-format = "murmur2"
hash = "412559289"

[update]
[update.curseforge]
file-id = 3545495
project-id = 409184
release-channel = "beta"
