name = "Clumps"
filename = "Clumps-fabric-1.18.1-8.0.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3575/673/Clumps-fabric-1.18.1-8.0.4.jar"
hash-format = "murmur2"
hash = "543987379"

[update]
[update.curseforge]
file-id = 3575673
project-id = 256717
release-channel = "beta"
