name = "Conjuring [Fabric/Forge]"
filename = "conjuring-1.0.19+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/326/conjuring-1.0.19+1.18.jar"
hash-format = "murmur2"
hash = "2857571480"

[update]
[update.curseforge]
file-id = 3606326
project-id = 422310
release-channel = "beta"
