name = "Customizable Player Models (Fabric)"
filename = "CustomPlayerModels-Fabric-1.17-0.1.1b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3480/348/CustomPlayerModels-Fabric-1.17-0.1.1b.jar"
hash-format = "murmur2"
hash = "816093124"

[update]
[update.curseforge]
file-id = 3480348
project-id = 440597
release-channel = "beta"
