name = "CustomSkinLoader"
filename = "CustomSkinLoader_Fabric-14.13-SNAPSHOT-311.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/744/CustomSkinLoader_Fabric-14.13-SNAPSHOT-311.jar"
hash-format = "murmur2"
hash = "1528009236"

[update]
[update.curseforge]
file-id = 3599744
project-id = 286924
release-channel = "beta"
