name = "DashLoader"
filename = "dashloader-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3383/467/dashloader-2.0.jar"
hash-format = "murmur2"
hash = "1828209857"

[update]
[update.curseforge]
file-id = 3383467
project-id = 472772
release-channel = "beta"
