name = "Drink Beer (Fabric)"
filename = "drinkbeer-v3.0.2 for 1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/314/drinkbeer-v3.0.2 for 1.18.1.jar"
hash-format = "murmur2"
hash = "3991070920"

[update]
[update.curseforge]
file-id = 3575314
project-id = 517119
release-channel = "beta"
