name = "Dynamic FPS"
filename = "dynamic-fps-2.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/973/dynamic-fps-2.1.0.jar"
hash-format = "murmur2"
hash = "3032445496"

[update]
[update.curseforge]
file-id = 3606973
project-id = 335493
release-channel = "beta"
