name = "Extra Origins"
filename = "extraorigins-1.17-9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3489/452/extraorigins-1.17-9.jar"
hash-format = "murmur2"
hash = "3205986032"

[update]
[update.curseforge]
file-id = 3489452
project-id = 398419
release-channel = "beta"
