name = "Forge Config API Port [Fabric]"
filename = "ForgeConfigAPIPort-v3.1.1-1.18.1-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/918/ForgeConfigAPIPort-v3.1.1-1.18.1-Fabric.jar"
hash-format = "murmur2"
hash = "1781722461"

[update]
[update.curseforge]
file-id = 3600918
project-id = 547434
release-channel = "beta"
