name = "Goblin Traders (Fabric)"
filename = "goblin-traders-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/200/goblin-traders-1.4.1.jar"
hash-format = "murmur2"
hash = "1005658894"

[update]
[update.curseforge]
file-id = 3543200
project-id = 534373
release-channel = "beta"
