name = "Icarus (Fabric)"
filename = "icarus-1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3495/463/icarus-1.4.jar"
hash-format = "murmur2"
hash = "2368207563"

[update]
[update.curseforge]
file-id = 3495463
project-id = 428151
release-channel = "beta"
