name = "Icarus"
filename = "icarus-1.8.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Dw7M6XKW/versions/1.8/icarus-1.8.jar"
hash-format = "sha512"
hash = "63e1c5b869d06e2bdd18ca09b3d3edb76ea3a389b1ba7816af5cd0aa95c08b517e65c11541b6f1fc2179e89f2bcec591426c71ab5f9ac9eca0c9b60c28b8667b"

[update]
[update.modrinth]
mod-id = "Dw7M6XKW"
version = "hrBwid8D"
