name = "Icarus (Fabric)"
filename = "icarus-1.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/600/icarus-1.9.jar"
hash-format = "murmur2"
hash = "1681708002"

[update]
[update.curseforge]
file-id = 3542600
project-id = 428151
release-channel = "beta"
