name = "Immersive Portals"
filename = "immersive-portals-1.2.3-mc1.18.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3614/451/immersive-portals-1.2.3-mc1.18.1-fabric.jar"
hash-format = "murmur2"
hash = "3989583138"

[update]
[update.curseforge]
file-id = 3614451
project-id = 332273
release-channel = "beta"
