name = "LambDynamicLights"
filename = "lambdynamiclights-2.0.2+1.17.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3409/38/lambdynamiclights-2.0.2+1.17.jar"
hash-format = "murmur2"
hash = "2350402653"

[update]
[update.curseforge]
file-id = 3409038
project-id = 393442
release-channel = "beta"

[option]
optional = true
default = false
description = "Adds dynamic lights while holding torches for example"
