name = "LittleTweaks"
filename = "littletweaks-0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3478/188/littletweaks-0.1.1.jar"
hash-format = "murmur2"
hash = "48414495"

[update]
[update.curseforge]
file-id = 3478188
project-id = 527975
release-channel = "beta"
