name = "Mod Menu"
filename = "modmenu-3.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/652/modmenu-3.0.1.jar"
hash-format = "murmur2"
hash = "3673623205"

[update]
[update.curseforge]
file-id = 3570652
project-id = 308702
release-channel = "beta"
