name = "Origins: The Planeswalker"
filename = "The Planeswalker - 2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3427/509/The Planeswalker - 2.0.1.jar"
hash-format = "murmur2"
hash = "2784263881"

[update]
[update.curseforge]
file-id = 3427509
project-id = 513097
release-channel = "beta"
