name = "Pehkui"
filename = "Pehkui-2.5.0+1.14.4-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3495/498/Pehkui-2.5.0+1.14.4-1.18.jar"
hash-format = "murmur2"
hash = "1152714459"

[update]
[update.curseforge]
file-id = 3495498
project-id = 319596
release-channel = "beta"
