name = "Public Gui Announcement"
filename = "Public GUI Announcement-fabric-1.18.1-3.2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/870/Public GUI Announcement-fabric-1.18.1-3.2.0.0.jar"
hash-format = "murmur2"
hash = "155351963"

[update]
[update.curseforge]
file-id = 3605870
project-id = 341727
release-channel = "beta"
