name = "Puzzles Lib [Fabric]"
filename = "PuzzlesLib-v3.1.3-1.18.1-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3583/447/PuzzlesLib-v3.1.3-1.18.1-Fabric.jar"
hash-format = "murmur2"
hash = "1261864905"

[update]
[update.curseforge]
file-id = 3583447
project-id = 547429
release-channel = "beta"
