name = "Screencopy"
filename = "screenshotcopy-1.0.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/92/screenshotcopy-1.0.0-fabric.jar"
hash-format = "murmur2"
hash = "177921897"

[update]
[update.curseforge]
file-id = 3631092
project-id = 574902
release-channel = "beta"
