name = "SlotLock"
filename = "slotlock-1.0.4-BETA+1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3541/401/slotlock-1.0.4-BETA+1.18.jar"
hash-format = "murmur2"
hash = "425614949"

[update]
[update.curseforge]
file-id = 3541401
project-id = 408366
release-channel = "beta"
