name = "spark"
filename = "spark-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3485/139/spark-fabric.jar"
hash-format = "murmur2"
hash = "156274226"

[update]
[update.curseforge]
file-id = 3485139
project-id = 361579
release-channel = "beta"
