name = "Trinkets (Fabric)"
filename = "trinkets-3.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/826/trinkets-3.1.0.jar"
hash-format = "murmur2"
hash = "3390741003"

[update]
[update.curseforge]
file-id = 3542826
project-id = 341284
release-channel = "beta"
